
DROP TABLE IF EXISTS users;
create table users
(
    id         int  generated by default as identity PRIMARY KEY,
    email      varchar(128)                                    not null,
    first_name varchar(50)                                     not null,
    last_name  varchar(100)                                    not null,
    password   varchar(255)                                    not null,
    role       varchar(20) default 'USER'::character varying   not null,
    status     varchar(20) default 'ACTIVE'::character varying not null,
    registered timestamp   default now()                       not null
);
create unique index users_email_uindex on users (email);

DROP TABLE IF EXISTS giftcards;
CREATE TABLE giftCards
(
    id          int  generated by default as identity PRIMARY KEY,
    number      bigserial                                           NOT NULL,
    amount      decimal                                             NOT NULL,
    isPrint     boolean,
    status      varchar(20) default 'NEW'::character varying        not null,
    isGenerated boolean,
    typeCard    varchar(20) default 'SIMPLE'::character varying     not null,
    registered  timestamp   default now(),
    withdrawal  decimal,
    lastUpdate  timestamp   default now(),
    owner_id    varchar(20)
);
create unique index giftCards_number_index on giftCards (number);
